services:
  test-3.11:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.11"
    environment:
      - JAX_PLATFORMS=cpu

  test-3.12:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.12"
    environment:
      - JAX_PLATFORMS=cpu

  test-3.13:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.13"
    environment:
      - JAX_PLATFORMS=cpu

  test-3.14:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.14"
    environment:
      - JAX_PLATFORMS=cpu
